config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :cproducts
  resources :categories
  root "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/company.rb
class Company < ActiveRecord::Base
  searchkick
  has_attached_file :image, styles: { medium: "300x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/cproduct.rb
class Cproduct < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :image)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:title, :image)
    end
end

app/controllers/cproducts_controller.rb
class CproductsController < ApplicationController
  before_action :set_cproduct, only: [:show, :edit, :update, :destroy]

  # GET /cproducts
  # GET /cproducts.json
  def index
    @cproducts = Cproduct.all
  end

  # GET /cproducts/1
  # GET /cproducts/1.json
  def show
  end

  # GET /cproducts/new
  def new
    @cproduct = Cproduct.new
  end

  # GET /cproducts/1/edit
  def edit
  end

  # POST /cproducts
  # POST /cproducts.json
  def create
    @cproduct = Cproduct.new(cproduct_params)

    respond_to do |format|
      if @cproduct.save
        format.html { redirect_to @cproduct, notice: 'Cproduct was successfully created.' }
        format.json { render :show, status: :created, location: @cproduct }
      else
        format.html { render :new }
        format.json { render json: @cproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cproducts/1
  # PATCH/PUT /cproducts/1.json
  def update
    respond_to do |format|
      if @cproduct.update(cproduct_params)
        format.html { redirect_to @cproduct, notice: 'Cproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @cproduct }
      else
        format.html { render :edit }
        format.json { render json: @cproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cproducts/1
  # DELETE /cproducts/1.json
  def destroy
    @cproduct.destroy
    respond_to do |format|
      format.html { redirect_to cproducts_url, notice: 'Cproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cproduct
      @cproduct = Cproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cproduct_params
      params.require(:cproduct).permit(:title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/cproducts_helper.rb
module CproductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, html: { :multipart => true } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="assets/Pricecheck.jpg" alt="Price">
      <div class="carousel-caption cap">
        <h3>Chania</h3>
        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
      </div>
    </div>

    <div class="item">
      <img src="assets/Pricecheck.jpg" alt="Price">
      <div class="carousel-caption">
        <h3>Chania</h3>
        <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
      </div>
    </div>

    <div class="item">
      <img src="assets/Pricecheck.jpg" alt="Price">
      <div class="carousel-caption">
        <h3>Flowers</h3>
        <p>Beatiful flowers in Kolymbari, Crete.</p>
      </div>
    </div>

    <div class="item">
      <img src="assets/Pricecheck.jpg" alt="Price">
      <div class="carousel-caption">
        <h3>Flowers</h3>
        <p>Beatiful flowers in Kolymbari, Crete.</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



  <div class="container ">
  <div class="row">
    <h1> Categories </h1>
    <% @categories.each do |category| %>
      <div class="col-sm-4 col-md-4">
        <div class="thumbnail">

          <%= image_tag category.image.url(:medium) %>
          <hr class="line">
          <h3 class="cheading">
          <%= category.title %></h3>

        <%= link_to 'Show', cproducts_path %>
        <%= link_to 'Edit', edit_category_path(category) %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= image_tag @category.image.url(:medium) %>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/companies/_form.html.erb
<%= form_for @company, html: { :multipart => true }  do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>


<div class="container">
<div class="row">
    <% @companies.each do |company| %>
      <div class="col-sm3 col-md-4">

        <div class="thumbnail">

          <%= image_tag company.image.url(:medium) %>
            <hr class="line">
            <h3 class="cheading">
          <%= company.title %>
        </h3>

        <%= link_to 'Show', companies_path %>
        <%= link_to 'Edit', edit_company_path(company) %>
        <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @company.title %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/cproducts/_form.html.erb
<%= form_for @cproduct, html: { :multipart => true }  do |f| %>
  <% if @cproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cproduct.errors.count, "error") %> prohibited this cproduct from being saved:</h2>

      <ul>
      <% @cproduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cproducts/edit.html.erb
<h1>Editing Cproduct</h1>

<%= render 'form' %>

<%= link_to 'Show', @cproduct %> |
<%= link_to 'Back', cproducts_path %>

app/views/cproducts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food and groceries products</h1>

<div class="container">
<div class="row">
    <% @cproducts.each do |cproduct| %>
      <div class="col-sm3 col-md-4">
      
        <div class="thumbnail">

          <%= image_tag cproduct.image.url(:medium) %>
            <hr class="line">
            <h3 class="cheading">
          <%= cproduct.title %>
        </h3>

        <%= link_to 'Show', companies_path %>
        <%= link_to 'Edit', edit_cproduct_path(cproduct) %>
        <%= link_to 'Destroy', cproduct, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Cproduct', new_cproduct_path %>

app/views/cproducts/new.html.erb
<h1>New Cproduct</h1>

<%= render 'form' %>

<%= link_to 'Back', cproducts_path %>

app/views/cproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cproduct.title %>
</p>

<%= link_to 'Edit', edit_cproduct_path(@cproduct) %> |
<%= link_to 'Back', cproducts_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a class="navbar-brand head" href="#">Bargain</a>
    <form class="navbar-form navbar-right" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bargain</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:800italic,400,800,600' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>

<%= yield %>

</body>
</html>